function [fitresult, gof] = planeFit(XL_sf3d, YL_sf3d, ZL_sf3d)
%CREATEFIT(XL_SF3D,YL_SF3D,ZL_SF3D)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : XL_sf3d
%      Y Input : YL_sf3d
%      Z Output: ZL_sf3d
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 21-May-2013 16:11:53


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( XL_sf3d, YL_sf3d, ZL_sf3d );

% Set up fittype and options.
ft = fittype( 'poly11' );
opts = fitoptions( ft );
opts.Lower = [-Inf -Inf -Inf];
opts.Upper = [Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, [xData, yData], zData );
% legend( h, 'untitled fit 1', 'ZL_sf3d vs. XL_sf3d, YL_sf3d', 'Location', 'NorthEast' );
% % Label axes
% xlabel( 'XL_sf3d' );
% ylabel( 'YL_sf3d' );
% zlabel( 'ZL_sf3d' );
% grid on
% view( 2.5, -6.0 );


